// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmn2LffID2tO1SLmx95apB1Mf14uitQz8',
    appId: '1:454260650486:web:de1317c4bcb6d13897d7d7',
    messagingSenderId: '454260650486',
    projectId: 'flutter-hub-a5694',
    authDomain: 'flutter-hub-a5694.firebaseapp.com',
    storageBucket: 'flutter-hub-a5694.appspot.com',
    measurementId: 'G-RYWYBHL8WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_JxMiu4qHN6WsFrsVdwU5LtR8eJIBiUs',
    appId: '1:454260650486:android:d7cec1f3a1bdebb097d7d7',
    messagingSenderId: '454260650486',
    projectId: 'flutter-hub-a5694',
    storageBucket: 'flutter-hub-a5694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxv1J8bHkacBPWcbSCS18oJKz6Wj4IaR8',
    appId: '1:454260650486:ios:8b17802b829046d097d7d7',
    messagingSenderId: '454260650486',
    projectId: 'flutter-hub-a5694',
    storageBucket: 'flutter-hub-a5694.appspot.com',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxv1J8bHkacBPWcbSCS18oJKz6Wj4IaR8',
    appId: '1:454260650486:ios:8b17802b829046d097d7d7',
    messagingSenderId: '454260650486',
    projectId: 'flutter-hub-a5694',
    storageBucket: 'flutter-hub-a5694.appspot.com',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmn2LffID2tO1SLmx95apB1Mf14uitQz8',
    appId: '1:454260650486:web:82c9a7ced50698de97d7d7',
    messagingSenderId: '454260650486',
    projectId: 'flutter-hub-a5694',
    authDomain: 'flutter-hub-a5694.firebaseapp.com',
    storageBucket: 'flutter-hub-a5694.appspot.com',
    measurementId: 'G-HCY7MHLTTD',
  );
}
